//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmOuting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegalRecruitingEntities : DbContext
    {
        public LegalRecruitingEntities()
            : base("name=LegalRecruitingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttorneyOuting> AttorneyOutings { get; set; }
        public DbSet<AttorneyOutingMailTemplate> AttorneyOutingMailTemplates { get; set; }
        public DbSet<AttorneyOutingAuthentication> AttorneyOutingAuthentications { get; set; }
    }
}
