//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmOuting
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttorneyOuting
    {
        public int AttorneyOutingID { get; set; }
        public string NameTagFirstName { get; set; }
        public string NameTagMiddleName { get; set; }
        public string NameTagLastName { get; set; }
        public string PersonType { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmailAddress { get; set; }
        public string BringingGuest { get; set; }
        public string AttendingOuting { get; set; }
        public string MealsLunch { get; set; }
        public string MealsDinner { get; set; }
        public string DietaryRestrictions { get; set; }
        public string BusToSunningdale { get; set; }
        public string BusToNYC { get; set; }
        public string TennisPlaying { get; set; }
        public string TennisRentRacquet { get; set; }
        public string TennisLevelOfPlay { get; set; }
        public string TennisMorning { get; set; }
        public string TennisAfternoon { get; set; }
        public string GolfPlaying { get; set; }
        public string GolfLevelOfPlay { get; set; }
        public string GolfMorning { get; set; }
        public string GolfClinicMorning { get; set; }
        public string GolfAfternoon { get; set; }
        public string GolfClinicAfternoon { get; set; }
        public string GolfRentClubs { get; set; }
        public string GolfClubRightLeft { get; set; }
        public string GolfCartOrWalk { get; set; }
        public string GolfFoursome { get; set; }
        public string BasketballOpenPlay { get; set; }
        public string BasketballOrganizedGame { get; set; }
        public string SpaInterest { get; set; }
        public string SpaManicure { get; set; }
        public string SpaPedicure { get; set; }
        public string SpaMiniMassage { get; set; }
        public string YogaInterest { get; set; }
        public string YogaSkillLevel { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    }
}
